development:
  adapter: postgresql
  database: emberwang_development
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  database: emberwang_production
  user: root
  pool: 5
  timeout: 5000
